CAA_TestApp/Models/Inventory.cs
using System.ComponentModel.DataAnnotations;
using System.Text.Json.Serialization;

namespace CAA_TestApp.Models
{
    public class Inventory : Auditable,  IValidatableObject, ICloneable
    {
        public int ID { get; set; }
        
        public string ISBN { get; set; }

        [Display(Name = "Quantity")]
        [Required(ErrorMessage ="Quantity cannot be left blank.")]
        public int Quantity { get; set; }

        [Display(Name = "Notes")]
        [StringLength(500, ErrorMessage ="Notes cannot be longer than 500 characters.")]
        public string Notes { get; set; }

        [Display(Name = "Shelf")]
        public string ShelfOn { get; set; }

        [Required(ErrorMessage ="You must enter a cost for the inventory total.")]
        [Range(0.0, 10000.00, ErrorMessage = "Cost must be between $0 and $10,000.00")]
        [DataType(DataType.Currency)]
        public double Cost { get; set; }

        [Display(Name = "Date Received")]
        [Required(ErrorMessage = "Date received cannot be left blank.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime DateReceived { get; set; }

        /*[ScaffoldColumn(false)]
        [Timestamp]
        public Byte[] RowVersion { get; set; }//Added for concurrency*/


        [Display(Name = "Location")]
        [Required(ErrorMessage ="Select the location for this inventory record.")]
        public int LocationID { get; set; }

        [Display(Name = "Product")]
        [Required(ErrorMessage ="Select the product for this inventory record.")]
        public int ProductID { get; set; }

        [Display(Name = "Location")]
        public Location Location { get; set; }

        [Display(Name = "Product")]
        public Product Product { get; set; }

        public ItemPhoto ItemPhoto { get; set; }

        public ItemThumbnail ItemThumbnail { get; set; }

        public QrImage QRImage { get; set; }

        [JsonIgnore]
        public ICollection<Product> Products { get; set; } = new HashSet<Product>();

        [JsonIgnore]
        public ICollection<EventInventory> EventInventories { get; set; } = new HashSet<EventInventory>();
        
        [Display(Name = "Status")]
        public int statusID { get; set; }
        
        [Display(Name = "Status")]
        public Status Status { get; set; }


        //Methods
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            if (DateReceived > DateTime.Today)
            {
                yield return new ValidationResult("Date received cannot be in the future.", new[] { "DateReceived" });
            }
            else if(Quantity < 0)
            {
                yield return new ValidationResult("Quantity cannot be below 0.", new[] { "Quantity" });
            }
            else if(Quantity > 500)
            {
                yield return new ValidationResult("Quantity cannot be greater than 500.", new[] { "Quantity" });
            }
        }

        public object Clone()
        {
            return this.MemberwiseClone();
        }
    }
}

CAA_TestApp/Controllers/InventoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CAA_TestApp.Data;
using CAA_TestApp.Models;
using System.Drawing.Imaging;
using System.Drawing;
using CAA_TestApp.Utilities;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using Microsoft.EntityFrameworkCore.Storage;
using System.Reflection;
using CAA_TestApp.ViewModels;
using DinkToPdf;
using DinkToPdf.Contracts;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.CodeAnalysis;
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using System.Security.Policy;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using System.IO;
using QRCoder;
using ZXing;
using Microsoft.AspNetCore.Authorization;

namespace CAA_TestApp.Controllers
{
    [Authorize]
    public class InventoriesController : Controller
    {
        private readonly CaaContext _context;

        private Random r = new Random();

        private int SendToken;

        public InventoriesController(CaaContext context)
        {
            _context = context;
        }

        // GET: Inventories
        public async Task<IActionResult> Index(string sortDirectionCheck, string sortFieldID, string SearchName, int? CategoryID, int[] LocationID,
            int? page, string actionButton, int? pageSizeID, string sortDirection = "asc", string sortField = "Inventory")
        {
            CheckDateForTakeInvBasedOnEvent();
            PopulateDropDownListsCategories();
            PopulateDropDownListsLocations();

            ViewData["Context"] = _context;

            ViewData["Filtering"] = "btn-outline-secondary ";

            string[] sortOptions = new[] { "Product", "Quantity", "Cost", "Location" };

            var inventories = _context.Inventories
                .Include(i => i.Location)
                .Include(i => i.Status)
                .Include(i => i.Product)
                .ThenInclude(c => c.Category)
                .Include(i => i.ItemThumbnail).OrderBy(i => i.Product.Name).ThenBy(i => i.Location.City)
                .AsNoTracking();

            if (CategoryID.HasValue)
            {
                inventories = inventories.Where(p => p.Product.CategoryID == CategoryID);
                ViewData["Filtering"] = " btn-danger";
            }
            if (LocationID.Length > 0)
            {
                inventories = inventories.Where(p => LocationID.Contains(p.LocationID));
                ViewData["Filtering"] = "  btn-danger ";
            }
            if (!String.IsNullOrEmpty(SearchName))
            {
                inventories = inventories.Where(p => p.Product.Name.ToUpper().Contains(SearchName.ToUpper()) || p.ISBN.Contains(SearchName));
                ViewData["Filtering"] = " btn-danger";
            }

            //See if we have called for a change of filtering or sorting
            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted!
            {
                page = 1; //Reset page to start

                if (sortOptions.Contains(actionButton)) //Change of sort is requested
                {
                    if (actionButton == sortField)
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton; //sort by the button clicked
                }
                else
                {
                    sortDirection = String.IsNullOrEmpty(sortDirectionCheck) ? "asc" : "desc";
                    sortField = sortFieldID;
                }
            }
            //Now we know which field and direction to sort by
            if (sortField == "Location")
            {
                if (sortDirection == "asc")
                {
                    inventories = inventories
                        .OrderBy(i => i.Location.City)
                        .ThenBy(i => i.Product.Name);
                }
                else
                {
                    inventories = inventories
                        .OrderByDescending(i => i.Location.City)
                        .ThenBy(i => i.Product.Name);
                }
            }
            else if (sortField == "Product")
            {
                if (sortDirection == "desc")
                {
                    inventories = inventories
                        .OrderByDescending(i => i.Product.Name)
                        .ThenByDescending(i => i.Location.City);
                }
                else
                {
                    inventories = inventories
                    .OrderBy(i => i.Product.Name)
                    .ThenBy(i => i.Location.City);

                }
            }
            else if (sortField == "Quantity")
            {
                if (sortDirection == "asc")
                {
                    inventories = inventories
                        .OrderByDescending(i => i.Quantity)
                        .ThenBy(i => i.Location.City);
                }
                else
                {
                    inventories = inventories
                        .OrderBy(i => i.Quantity)
                        .ThenBy(i => i.Location.City);
                }
            }
            if (sortField == "Category") //sort by category
            {
                if (sortDirection == "asc")
                {
                    if (sortDirection == "asc")
                    {
                        inventories = inventories
                            .OrderBy(i => i.Product.Category.Classification);
                    }
                    else
                    {
                        inventories = inventories
                            .OrderByDescending(i => i.Product.Category.Classification);
                    }
                }
            }
            else if (sortField == "Status") //sort by category
            {
                if (sortDirection == "asc")
                {
                    if (sortDirection == "asc")
                    {
                        inventories = inventories
                            .OrderBy(i => i.Status.status);
                    }
                    else
                    {
                        inventories = inventories
                            .OrderByDescending(i => i.Status.status);
                    }
                }
            }
            //Set sort for next time
            ViewData["sortField"] = sortField;
            ViewData["sortDirection"] = sortDirection;
            //SelectList for sorting options
            ViewBag.sortFieldID = new SelectList(sortOptions, sortField.ToString());

            //Handle paging
            int pageSize = PageSizeHelper.SetPageSize(HttpContext, pageSizeID, "inventories");
            ViewData["pageSizeID"] = PageSizeHelper.PageSizeList(pageSize);
            var pagedData = await PaginatedList<Inventory>.CreateAsync(inventories.AsNoTracking(), page ?? 1, pageSize);

            return View(pagedData);
        }

        public async Task<IActionResult> Archived(string sortDirectionCheck, string sortFieldID, string SearchName, int? CategoryID, int? LocationID,
            int? page, string actionButton, int? pageSizeID, string sortDirection = "asc", string sortField = "Inventory")
        {
            PopulateDropDownListsCategories();
            PopulateDropDownListsLocations();

            ViewData["Context"] = _context;

            ViewData["Filtering"] = "btn-outline-secondary ";

            string[] sortOptions = new[] { "Product", "Quantity", "Cost", "Location" };

            var inventories = _context.Inventories
                .Include(i => i.Location)
                .Include(i => i.Status)
                .Include(i => i.Product)
                .ThenInclude(c => c.Category)
                .Where(i => i.statusID == _context.statuses.FirstOrDefault(i => i.status == "Archived").ID)
                .AsNoTracking();

            if (CategoryID.HasValue)
            {
                inventories = inventories.Where(p => p.Product.CategoryID == CategoryID);
                ViewData["Filtering"] = " btn-danger";
            }
            if (LocationID.HasValue)
            {
                inventories = inventories.Where(p => p.LocationID == LocationID);
                ViewData["Filtering"] = "  btn-danger ";
            }
            if (!String.IsNullOrEmpty(SearchName))
            {
                inventories = inventories.Where(p => p.Product.Name.ToUpper().Contains(SearchName.ToUpper()));
                ViewData["Filtering"] = " btn-danger";
            }

            //See if we have called for a change of filtering or sorting
            if (!String.IsNullOrEmpty(actionButton)) //Form Submitted!
            {
                page = 1; //Reset page to start

                if (sortOptions.Contains(actionButton)) //Change of sort is requested
                {
                    if (actionButton == sortField)
                    {
                        sortDirection = sortDirection == "asc" ? "desc" : "asc";
                    }
                    sortField = actionButton; //sort by the button clicked
                }
                else
                {
                    sortDirection = String.IsNullOrEmpty(sortDirectionCheck) ? "asc" : "desc";
                    sortField = sortFieldID;
                }
            }
            //Now we know which field and direction to sort by
            if (sortField == "Location")
            {
                if (sortDirection == "asc")
                {
                    inventories = inventories
                        .OrderBy(i => i.Location.City)
                        .ThenBy(i => i.Product.Name);
                }
                else
                {
                    inventories = inventories

CAA_TestApp/Views/Inventories/Archive.cshtml
@model CAA_TestApp.Models.Inventory

@{
    ViewData["Title"] = "Archive";
}

<h1>Archive @Html.DisplayFor(model => model.Product.Name)</h1>


<div>

    <hr />
    <dl class="row">
        <!--  <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.ISBN)
          </dt>
          <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.ISBN)
          </dd> -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <!--     <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Notes)
          </dd> -->
        <!--   <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.ShelfOn)
           </dt>
           <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.ShelfOn)
           </dd> -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <!--     <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.DateReceived)
        </dt>
        <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.DateReceived)
        </dd> -->
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Location.City)
        </dd>
    </dl>
    <h2 style="font-size: 16px; color:red;">Are you sure you want to archive this?</h2>
    <form asp-action="Archive">
        <input type="hidden" asp-for="ID" />
        <input type="submit" title="Click here to archive the item" value="Archive" class="btn btn-danger btn-style" /> 
        <a asp-action="Index" title="Click here to go back to main Inventory page" class="btn btn-outline-dark btn-style ">Back to List</a>
    </form>
</div>

CAA_TestApp/Views/Inventories/Delete.cshtml
@model CAA_TestApp.Models.Inventory

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete Inventory</h1>


<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShelfOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShelfOn)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateReceived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateReceived)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Location)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Location.ID)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ID)
        </dd>
    </dl>
    <h2 style="font-size: 16px; color:red;">Are you sure you want to delete this?</h2>
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" title="Click here to delete the record" value="Delete" class="btn btn-danger btn-style" /> |
        <a asp-action="Index" title=" Click here to go back to main Inventory page" class="btn btn-outline-dark btn-style ">Back to List</a>
    </form>
</div>

CAA_TestApp/Views/Inventories/InventoryReports.cshtml
@model IEnumerable<CAA_TestApp.ViewModels.InventoryReportsVM>

@{
    ViewData["Title"] = "Inventory Reports";
}

<h1>Inventory Report</h1>
<form asp-controller="Inventories" method="get">
<a asp-action="DownloadInventoriesReports" title=" Click here to download the Invetory Report" class="btn btn-info float-end btn-style">Download Inventory Report</a>
    <div class="form-horizontal">
        <button class=" btn btn-style  @(ViewData["Filtering"]) " type="button" data-bs-toggle="collapse" id="filterToggle" data-bs-target="#collapseFilter"
                title=" Click here to filter or search records" aria-expanded="false" aria-controls="collapseFilter" style="border-radius: 25px;">
            Filter/Search
        </button>
        <br />
        <br />

        <div class="collapse" id="collapseFilter">
            <div class="card card-body bg-light">
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="control-label">Search Item Name:</label>
                        @Html.TextBox("SearchName", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label">Filter by Branches: (Ctrl + Click to Select Multiple)</label>
                        @Html.ListBox("LocationID", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4 align-self-end" style="margin-top:5px;">
                        <input type="submit" title=" Click here to filter records" name="actionButton" value="Filter" class="btn btn-outline-primary btn-style" />
                        <a asp-action="InventoryReports" title=" Click here to clear the filter" class="btn btn-outline-dark btn-style ">Clear</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Product)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cost)
            </th>

            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Category)
            </th>
            


        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Product)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cost)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Category)
                </td>
               
        </tr>
}
    </tbody>
</table>
<partial name="_PagingNavBar" />
</form>

CAA_TestApp/Views/Inventories/LowStockReports.cshtml
@model IEnumerable<CAA_TestApp.ViewModels.LowStockReportsVM>
@{
    ViewData["Title"] = "LowStockReports";
}

<h1>Low Stock Report</h1>
<form asp-controller="Inventories" asp-action="LowStockReports" method="get">
    <a asp-action="DownloadLowStockReports" title=" Click here to download Low stock reports" class="btn btn-info float-end btn-style">Download Low Stock Report</a>
    <div class="form-horizontal">
        <button class=" btn btn-style  @(ViewData["Filtering"]) " type="button" data-bs-toggle="collapse" id="filterToggle"
            title=" Click here to filter or search records" data-bs-target="#collapseFilter" aria-expanded="false" aria-controls="collapseFilter" style="border-radius: 25px;">
            Filter/Search
        </button>
        <br />
        <br />

        <div class="collapse" id="collapseFilter">
            <div class="card card-body bg-light">
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="control-label">Search Item Name:</label>
                        @Html.TextBox("SearchName", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label">Filter by Branches: (Ctrl + Click to Select Multiple)</label>
                        @Html.ListBox("LocationID", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4 align-self-end" style="margin-top:5px;">
                        <input type="submit" title="Click here to filter the records" name="actionButton" value="Filter" class="btn btn-outline-primary btn-style" />
                        <a asp-action="LowStockReports" title=" Click here to clear the filter" class="btn btn-outline-dark btn-style ">Clear</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Product)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>

                <th>
                    @Html.DisplayNameFor(model => model.ParLevel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cost)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Location)
                </th>



            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ParLevel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <partial name="_PagingNavBar" />
</form>

CAA_TestApp/Views/Inventories/NoStockReports.cshtml
@using CAA_TestApp.Data;
@model IEnumerable<CAA_TestApp.ViewModels.NoStockReportsVM>
@{
    ViewData["Title"] = "Zero Stock Reports";
}

<h1>Zero Stock Report</h1>
<form asp-controller="Inventories" asp-action="NoStockReports" method="get">
    <a asp-action="DownloadNoStockReports" title=" Click here to download No Stock reports" class="btn btn-info float-end btn-style">Download No Stock Report</a>
    <div class="form-horizontal">
        <button class=" btn btn-style @(ViewData["Filtering"]) " type="button" data-bs-toggle="collapse" id="filterToggle" data-bs-target="#collapseFilter"
                title=" Click here to filter and search records " aria-expanded="false" aria-controls="collapseFilter" style="border-radius: 25px;">
            Filter/Search
        </button>
        <br />
        <br />
       
        <div class="collapse" id="collapseFilter">
            <div class="card card-body bg-light">
                <br />
                <div class="row">
                    <div class="form-group col-md-4">
                        <label class="control-label">Search Item Name:</label>
                        @Html.TextBox("SearchName", null, new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4">
                        <label class="control-label">Filter by Branches: (Ctrl + Click to Select Multiple)</label>
                        @Html.ListBox("LocationID", null, htmlAttributes: new { @class = "form-control" })
                    </div>
                    <div class="form-group col-md-4 align-self-end" style="margin-top:5px;">
                        <input type="submit" title=" Click here to filter " name="actionButton" value="Filter" class="btn btn-outline-primary btn-style" />
                        <a asp-action="NoStockReports" title=" Click here to clear the filter" class="btn btn-outline-dark btn-style ">Clear</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Product)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ParLevel)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cost)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Location)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Product)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Category)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantity)
                    </td>

                    <td>
                        @Html.DisplayFor(modelItem => item.ParLevel)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Cost)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Location)
                    </td>

                </tr>
            }
        </tbody>
    </table>
    <partial name="_PagingNavBar" />
</form>

CAA_TestApp/Views/Inventories/SendInv.cshtml
@model CAA_TestApp.Models.Inventory


@{
    ViewData["Title"] = "Send Inventory";
}

<form asp-action="SendInv" method="post"> 
<h1>@Html.DisplayFor(model => model.Product.Name)</h1>
<div>
    <hr />
        @{
        if (Model.ItemPhoto?.Content != null)
        {
                            @:<div>
                string imageBase64 = Convert.ToBase64String(Model.ItemPhoto.Content);
                string imageSrc = string.Format("data:" + Model.ItemPhoto.MimeType + ";base64,{0}", imageBase64);
                                <img src="@imageSrc" alt="Profile Picture of @Model.ISBN" title="Profile Picture of @Model.ISBN" class="img-fluid rounded" />
                            @:</div><hr />

        }
        }

    <dl class="row">
      @*<!--  <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ISBN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ISBN)
        </dd>-->*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
    @*
      <!--  <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ShelfOn)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ShelfOn)
        </dd>-->*@
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateReceived)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateReceived)
        </dd>
                <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Notes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Notes)
        </dd>
    </dl>
    @{
        ViewData["IsbnCode"] = ViewBag.ISBN;
     }


</div>


     <div>
        <label asp-for="Location.City" class="control-label"><strong>From: </strong></label>
        <input asp-for="Location.City" name="locationFrom" class="form-control" value="@ViewBag.locFrom" readonly>
     </div>
     <div >
        <label asp-for="LocationID" class="control-label"><strong>To:</strong></label><br />
        <span style="color:red">@ViewBag.SameLocs</span>
        <select asp-for="LocationID" name="locationTo" class="form-control" asp-items="ViewBag.LocationID" ></select>
        <span asp-validation-for="LocationID" class="text-danger"></span>
     </div>
    <div>
        <div class="col-lg-6 col-lg-offset-3" style="margin-top:20px;">
            <label><strong>Quantity:</strong></label><br />
            <span style="color:red">@ViewBag.OverQuan</span><br />
            <input type="number" name="quantity" value="@ViewBag.quanValue" min="0" required/>
        </div>
        <br />
    </div>
        <h2 style="font-size: 16px; color:red;">Are you sure you want to Transfer this?</h2>

    <div class="form-group" style="margin-top:20px;">
 
         <input name="submit" value="Yes"  type="submit" class="btn btn-primary btn-style" href="@Url.Action("ItemTransfered","Inventories")" data-toggle="modal" data-target="#exampleModal" 
         style="width:75px; margin-right: 15px;">
        <a asp-action="Index" class="btn btn-outline-dark btn-style " >Back to List</a>
    </div>

 </form>
 <br/>